name: Node.js CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '24'

    - name: Frontend Compilation (Lint JSX/JS)
      run: |
        cd client
        npm ci
        # Run ESLint on all JS/JSX files
        npx eslint . --ext .js,.jsx

    - name: Backend Compilation (Syntax Check)
      run: |
        cd api
        for file in $(find . -name "*.js"); do
          echo "Checking $file"
          node --check "$file" || exit 1
        done

  gitleaks-scan:
    needs: compile
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Checkout gitleaks
      uses: gitleaks/gitleaks-action@v2
    - name: Gitleak Scan
      run: |
        gitleaks detect --source ./client --exit-code 1
        gitleaks detect --source ./api --exit-code 1
